project_id = "lozdvdytcbpfhjveghzz"

[functions.hl7-receiver]
verify_jwt = false

[functions.parse-bank-statement]
verify_jwt = false

[functions.classify-transactions]
verify_jwt = false

[functions.portal-patient-access]
verify_jwt = false

[functions.portal-doctor-access]
verify_jwt = false
