import { supabase } from "@/integrations/supabase/client";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import StatusBadge from "@/components/StatusBadge";
import { Search, Plus } from "lucide-react";
import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { useAuth } from "@/hooks/useAuth";

const Orders = () => {
  const [search, setSearch] = useState("");
  const [open, setOpen] = useState(false);
  const queryClient = useQueryClient();
  const { user } = useAuth();

  const { data: orders = [], isLoading } = useQuery({
    queryKey: ["orders"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("orders")
        .select("*, patients(name)")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data;
    },
  });

  const { data: patients = [] } = useQuery({
    queryKey: ["patients"],
    queryFn: async () => {
      const { data, error } = await supabase.from("patients").select("id, name").order("name");
      if (error) throw error;
      return data;
    },
  });

  const createMutation = useMutation({
    mutationFn: async (form: { patient_id: string; doctor_name: string; insurance: string; exams: string[]; priority: string }) => {
      const { error } = await supabase.from("orders").insert({
        ...form,
        order_number: "", // auto-generated by trigger
        created_by: user?.id,
      });
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["orders"] });
      setOpen(false);
      toast.success("Pedido criado com sucesso!");
    },
    onError: (e: any) => toast.error(e.message),
  });

  const filtered = orders.filter(o => {
    const patientName = (o.patients as any)?.name || "";
    return patientName.toLowerCase().includes(search.toLowerCase()) || o.order_number.toLowerCase().includes(search.toLowerCase());
  });

  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Pedidos</h1>
          <p className="text-sm text-muted-foreground">Gerenciamento de pedidos de exames</p>
        </div>
        <Dialog open={open} onOpenChange={setOpen}>
          <DialogTrigger asChild>
            <Button><Plus className="w-4 h-4 mr-2" />Novo Pedido</Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader><DialogTitle>Criar Pedido</DialogTitle></DialogHeader>
            <OrderForm patients={patients} onSubmit={data => createMutation.mutate(data)} loading={createMutation.isPending} />
          </DialogContent>
        </Dialog>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <div className="relative max-w-sm">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input placeholder="Buscar pedido ou paciente..." value={search} onChange={e => setSearch(e.target.value)} className="pl-9" />
          </div>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <p className="text-center py-8 text-muted-foreground">Carregando...</p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Pedido</TableHead>
                  <TableHead>Paciente</TableHead>
                  <TableHead>Médico</TableHead>
                  <TableHead>Convênio</TableHead>
                  <TableHead>Exames</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Prioridade</TableHead>
                  <TableHead>Data</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filtered.map(order => (
                  <TableRow key={order.id}>
                    <TableCell className="font-mono text-sm font-medium">{order.order_number}</TableCell>
                    <TableCell>{(order.patients as any)?.name}</TableCell>
                    <TableCell className="text-sm">{order.doctor_name}</TableCell>
                    <TableCell className="text-sm">{order.insurance}</TableCell>
                    <TableCell className="text-sm">{order.exams?.join(", ")}</TableCell>
                    <TableCell><StatusBadge status={order.status} /></TableCell>
                    <TableCell><StatusBadge status={order.priority} /></TableCell>
                    <TableCell className="text-sm">{new Date(order.created_at).toLocaleDateString("pt-BR")}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

const OrderForm = ({ patients, onSubmit, loading }: { patients: { id: string; name: string }[]; onSubmit: (data: any) => void; loading: boolean }) => {
  const [form, setForm] = useState({
    patient_id: "", doctor_name: "", insurance: "Particular", exams: [] as string[], priority: "normal",
  });
  const [examInput, setExamInput] = useState("");

  const addExam = () => {
    if (examInput.trim()) {
      setForm(f => ({ ...f, exams: [...f.exams, examInput.trim()] }));
      setExamInput("");
    }
  };

  return (
    <form onSubmit={e => { e.preventDefault(); onSubmit(form); }} className="space-y-4">
      <div className="space-y-2">
        <Label>Paciente</Label>
        <Select value={form.patient_id} onValueChange={v => setForm(f => ({ ...f, patient_id: v }))}>
          <SelectTrigger><SelectValue placeholder="Selecionar paciente" /></SelectTrigger>
          <SelectContent>
            {patients.map(p => <SelectItem key={p.id} value={p.id}>{p.name}</SelectItem>)}
          </SelectContent>
        </Select>
      </div>
      <div className="grid grid-cols-2 gap-4">
        <div className="space-y-2">
          <Label>Médico Solicitante</Label>
          <Input value={form.doctor_name} onChange={e => setForm(f => ({ ...f, doctor_name: e.target.value }))} required />
        </div>
        <div className="space-y-2">
          <Label>Convênio</Label>
          <Input value={form.insurance} onChange={e => setForm(f => ({ ...f, insurance: e.target.value }))} />
        </div>
      </div>
      <div className="space-y-2">
        <Label>Prioridade</Label>
        <Select value={form.priority} onValueChange={v => setForm(f => ({ ...f, priority: v }))}>
          <SelectTrigger><SelectValue /></SelectTrigger>
          <SelectContent>
            <SelectItem value="normal">Normal</SelectItem>
            <SelectItem value="urgent">Urgente</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <div className="space-y-2">
        <Label>Exames</Label>
        <div className="flex gap-2">
          <Input value={examInput} onChange={e => setExamInput(e.target.value)} placeholder="Ex: Hemograma" onKeyDown={e => e.key === "Enter" && (e.preventDefault(), addExam())} />
          <Button type="button" variant="outline" onClick={addExam}>+</Button>
        </div>
        {form.exams.length > 0 && (
          <div className="flex flex-wrap gap-1 mt-2">
            {form.exams.map((exam, i) => (
              <span key={i} className="px-2 py-1 bg-secondary text-secondary-foreground rounded-md text-xs flex items-center gap-1">
                {exam}
                <button type="button" onClick={() => setForm(f => ({ ...f, exams: f.exams.filter((_, j) => j !== i) }))} className="hover:text-destructive">×</button>
              </span>
            ))}
          </div>
        )}
      </div>
      <Button type="submit" className="w-full" disabled={loading || !form.patient_id}>
        {loading ? "Salvando..." : "Criar Pedido"}
      </Button>
    </form>
  );
};

export default Orders;
